import { serializeGenBloxFile } from "./genblox-format.js";

export const AI_PROMPT = `This is a GenBlox game file.
Change the game as I describe, but keep all section markers.
Return the complete file as plain text without Markdown fences.

My idea: make the player collect stars and add three difficulty levels.`;

export const CLICKER_GAME = Object.freeze({
  manifest: { formatVersion: 1, templateId: "clicker-1", title: "Star Clicker", description: "Catch stars before time runs out.", mode: "solo", maxPlayers: 1, orientation: "any", sdkVersion: 1 },
  html: `<main class="game"><h1>⭐ Star Clicker</h1><p>Catch as many stars as you can!</p><button id="star" aria-label="Catch the star">⭐</button><div class="hud"><strong id="score">Score: 0</strong><span id="time">Time: 20</span></div><button id="start">Start game</button></main>`,
  css: `*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:linear-gradient(145deg,#201d42,#121122);color:#fff;font-family:system-ui,sans-serif}.game{text-align:center;width:min(92vw,620px)}h1{color:#b7f34a}#star{position:relative;width:92px;height:92px;border:0;border-radius:24px;background:#9478ff;font-size:48px;cursor:pointer;transition:transform .12s}.hud{display:flex;justify-content:center;gap:32px;margin:28px;font-size:20px}#start{padding:12px 22px;border:0;background:#b7f34a;color:#171525;font-weight:800;cursor:pointer}`,
  javascript: `const star=document.querySelector('#star');const scoreEl=document.querySelector('#score');const timeEl=document.querySelector('#time');const start=document.querySelector('#start');let score=0,timer=null,time=20;function move(){star.style.transform='translate('+(-220+Math.random()*440)+'px,'+(-80+Math.random()*160)+'px) rotate('+Math.random()*30+'deg)'}function reset(){clearInterval(timer);score=0;time=20;scoreEl.textContent='Score: 0';timeEl.textContent='Time: 20';start.hidden=false;move()}star.addEventListener('click',()=>{if(!timer)return;score++;scoreEl.textContent='Score: '+score;move()});start.addEventListener('click',()=>{reset();start.hidden=true;timer=setInterval(()=>{time--;timeEl.textContent='Time: '+time;if(time<=0){clearInterval(timer);timer=null;start.hidden=false;GenBlox.finish({score})}},1000)});GenBlox.ready();`,
});

export const CLICKER_FILE = serializeGenBloxFile(CLICKER_GAME);

export const TIC_TAC_TOE_GAME = Object.freeze({
  manifest: { formatVersion: 1, templateId: "tic-tac-toe-remix-1", title: "Tic-Tac-Toe Remix", description: "Play Tic-Tac-Toe against a friendly robot.", mode: "solo", maxPlayers: 1, orientation: "any", sdkVersion: 1 },
  html: `<main class="game"><p class="kicker">YOUR FIRST REMIX</p><h1>Tic-Tac-Toe</h1><p id="status" aria-live="polite">Your turn — you are X</p><div id="board" class="board" role="grid" aria-label="Tic-Tac-Toe board"></div><div class="score"><span>You <strong id="you">0</strong></span><span>Robot <strong id="bot">0</strong></span></div><button id="again">New round</button><small>Tip: ask AI to use animals, make a bigger board, or add difficulty levels.</small></main>`,
  css: `*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at top,#302b61,#12111f 62%);color:#f8f7ff;font-family:system-ui,sans-serif}.game{width:min(92vw,520px);text-align:center}.kicker{margin:0;color:#b7f34a;font-size:12px;font-weight:900;letter-spacing:2px}h1{margin:8px 0;font-size:clamp(36px,10vw,62px)}#status{min-height:24px;color:#c6c0db}.board{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;width:min(82vw,360px);aspect-ratio:1;margin:22px auto}.cell{border:1px solid #ffffff22;background:#211f36;color:#ff668c;font-size:clamp(38px,12vw,72px);font-weight:900;cursor:pointer}.cell[data-mark="O"]{color:#63dcff}.cell:disabled{cursor:default}.score{display:flex;justify-content:center;gap:35px;margin:18px;font-size:18px}.score strong{color:#b7f34a}#again{padding:12px 22px;border:0;background:#b7f34a;color:#171525;font-weight:900;cursor:pointer}small{display:block;margin:18px auto;color:#aaa7bd;line-height:1.5}`,
  javascript: `const boardEl=document.querySelector('#board');const statusEl=document.querySelector('#status');const again=document.querySelector('#again');const youEl=document.querySelector('#you');const botEl=document.querySelector('#bot');const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];let board,over,you=0,bot=0;function winner(){for(const [a,b,c] of wins)if(board[a]&&board[a]===board[b]&&board[a]===board[c])return board[a];return board.every(Boolean)?'draw':null}function draw(){boardEl.replaceChildren(...board.map((mark,index)=>{const cell=document.createElement('button');cell.className='cell';cell.dataset.mark=mark;cell.textContent=mark;cell.disabled=over||Boolean(mark);cell.setAttribute('aria-label',mark?'Cell '+(index+1)+': '+mark:'Empty cell '+(index+1));cell.onclick=()=>play(index);return cell}))}function finish(result){over=true;if(result==='X'){you++;youEl.textContent=you;statusEl.textContent='You win! 🎉'}else if(result==='O'){bot++;botEl.textContent=bot;statusEl.textContent='The robot wins this round.'}else statusEl.textContent='It is a draw — nice game!';draw();GenBlox.finish({result,score:you})}function check(){const result=winner();if(result)finish(result);return Boolean(result)}function botMove(){if(over)return;const empty=board.map((mark,index)=>mark?null:index).filter(index=>index!==null);const complete=(mark)=>{for(const line of wins){const marks=line.map(index=>board[index]);if(marks.filter(value=>value===mark).length===2&&marks.includes(''))return line[marks.indexOf('')]}return null};const choice=complete('O')??complete('X')??(board[4]===''?4:null)??empty[Math.floor(Math.random()*empty.length)];board[choice]='O';if(!check()){statusEl.textContent='Your turn — you are X';draw()}}function play(index){if(over||board[index])return;board[index]='X';draw();if(check())return;statusEl.textContent='Robot is thinking…';setTimeout(botMove,350)}function reset(){board=Array(9).fill('');over=false;statusEl.textContent='Your turn — you are X';draw()}again.onclick=reset;reset();GenBlox.ready();`,
});

export const TIC_TAC_TOE_FILE = serializeGenBloxFile(TIC_TAC_TOE_GAME);

export const CREATOR_TEMPLATES = Object.freeze({
  "tic-tac-toe": { file: TIC_TAC_TOE_FILE, filename: "tic-tac-toe-remix.genblox.txt" },
  clicker: { file: CLICKER_FILE, filename: "star-clicker.genblox.txt" },
});
